version: 0.0
os: linux
files:
  - source: app/
    destination: /tmp/deployment-archive/app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/restart_server.sh
      runas: root
